export const BookList = [
    {abr: "gen", term: "Genesis", chapters : 50 },
    {abr: "exo", term: "Exodus", chapters : 40 },
    {abr: "lev", term: "Leviticus" , chapters : 27 },
    {abr: "num", term: "Numeri" , chapters : 36},
    {abr: "deu", term: "Deuteronomium" , chapters : 34 },
    {abr: "jos", term: "Jozua" , chapters : 24},
    {abr: "jdg", term: "Richteren" , chapters : 21 },
    {abr: "rut", term: "Ruth" , chapters : 4 },
    {abr: "1sa", term: "1 Samuël" , chapters : 31},
    {abr: "1sa", term: "1 Samuel" , chapters : 31},
    {abr: "2sa", term: "2 Samuël" , chapters : 24},
    {abr: "2sa", term: "2 Samuel", chapters : 24},
    {abr: "1ki", term: "1 Koningen", chapters : 22},
    {abr: "2ki", term: "2 Koningen" , chapters : 25},
    {abr: "1ch", term: "1 Kronieken", chapters : 29},
    {abr: "2ch", term: "2 Kronieken" , chapters : 36},
    {abr: "ezr", term: "Ezra", chapters : 10},
    {abr: "neh", term: "Nehemia" , chapters : 13},
    {abr: "est", term: "Esther", chapters : 10},
    {abr: "est", term: "Ester", chapters : 10},
    {abr: "job", term: "Job", chapters : 42},
    {abr: "psa", term: "Psalmen", chapters : 150},
    {abr: "psa", term: "Psalm", chapters : 150},
    {abr: "pro", term: "Spreuken", chapters : 31},
    {abr: "ecc", term: "Prediker", chapters : 12},
    {abr: "sng", term: "Hooglied", chapters : 8},
    {abr: "isa", term: "Jesaja", chapters : 66},
    {abr: "jer", term: "Jeremia", chapters : 52},
    {abr: "lam", term: "Klaagliederen", chapters : 6},
    {abr: "ezk", term: "Ezechiël", chapters : 48},
    {abr: "ezk", term: "Ezechiel", chapters : 48},
    {abr: "dan", term: "Daniël", chapters : 12},
    {abr: "dan", term: "Daniel", chapters : 12},
    {abr: "hos", term: "Hosea", chapters : 14},
    {abr: "jol", term: "Joël", chapters : 3},
    {abr: "jol", term: "Joel", chapters : 3},
    {abr: "amo", term: "Amos", chapters : 9},
    {abr: "oba", term: "Obadja", chapters : 1},
    {abr: "jon", term: "Jona", chapters : 4},
    {abr: "mic", term: "Micha", chapters : 7},
    {abr: "nam", term: "Nahum", chapters : 3},
    {abr: "hab", term: "Habakuk", chapters : 3},
    {abr: "zep", term: "Sefanja", chapters : 3},
    {abr: "zep", term: "Sephanja", chapters : 3},
    {abr: "hag", term: "Haggaï", chapters : 2},
    {abr: "hag", term: "Haggai", chapters : 2},
    {abr: "zec", term: "Zacharia", chapters : 14},
    {abr: "mal", term: "Maleachi", chapters : 4},
    {abr: "mat", term: "Matteüs", chapters : 28},
    {abr: "mat", term: "Matteus", chapters : 28},
    {abr: "mat", term: "Mattheus", chapters : 28},
    {abr: "mat", term: "Mattheüs", chapters : 28},
    {abr: "mrk", term: "Marcus", chapters : 16},
    {abr: "mrk", term: "Markus", chapters : 16},
    {abr: "luk", term: "Lucas", chapters : 24},
    {abr: "luk", term: "Lukas", chapters : 24},
    {abr: "jhn", term: "Johannes", ignorePrefixes : ["3 ", "1 ", "2 ", ] , chapters : 21},
    {abr: "act", term: "Handelingen", chapters : 28},
    {abr: "rom", term: "Romeinen", chapters : 16},
    {abr: "1co", term: "1 Korintiërs", chapters : 16},
    {abr: "1co", term: "1 Korinthe", chapters : 16},
    {abr: "2co", term: "2 Korintiërs", chapters : 13},
    {abr: "2co", term: "2 Korinthe", chapters : 13},
    {abr: "gal", term: "Galaten", chapters : 6},
    {abr: "eph", term: "Efeziërs", chapters : 6},
    {abr: "eph", term: "Efeze", chapters : 6},
    {abr: "php", term: "Filippenzen", chapters : 4},
    {abr: "php", term: "Filippi", chapters : 4},
    {abr: "col", term: "Kolossenzen", chapters : 4},
    {abr: "col", term: "Kolosse", chapters : 4},
    {abr: "1th", term: "1 Tessalonicenzen", chapters : 5},
    {abr: "1th", term: "1 Thessalonicenzen", chapters : 5},
    {abr: "1th", term: "1 Thessalonika", chapters : 5},
    {abr: "1th", term: "1 Tessalonika", chapters : 5},
    {abr: "2th", term: "2 Tessalonicenzen", chapters : 3},
    {abr: "2th", term: "2 Thessalonicenzen", chapters : 3},
    {abr: "2th", term: "2 Thessalonika", chapters : 3},
    {abr: "2th", term: "2 Tessalonika", chapters : 3},
    {abr: "1ti", term: "1 Timoteüs", chapters : 6},
    {abr: "1ti", term: "1 Timotheüs", chapters : 6},
    {abr: "1ti", term: "1 Timoteus", chapters : 6},
    {abr: "1ti", term: "1 Timotheus", chapters : 6},
    {abr: "2ti", term: "1 Timoteüs", chapters : 6},
    {abr: "2ti", term: "2 Timotheüs", chapters : 4},
    {abr: "2ti", term: "2 Timoteus", chapters : 4},
    {abr: "2ti", term: "2 Timotheus", chapters : 4},
    {abr: "tit", term: "Titus", chapters : 3},
    {abr: "phm", term: "Filemon", chapters : 1},
    {abr: "heb", term: "Hebreeën", chapters : 13},
    {abr: "jas", term: "Jakobus", chapters : 5},
    {abr: "1pe", term: "1 Petrus", chapters : 5},
    {abr: "2pe", term: "2 Petrus", chapters : 3},
    {abr: "1jn", term: "1 Johannes", chapters : 5},
    {abr: "2jn", term: "2 Johannes", chapters : 1},
    {abr: "3jn", term: "3 Johannes", chapters : 1},
    {abr: "jud", term: "Judas", chapters : 1},
    {abr: "rev", term: "Openbaring", chapters : 22}
];